use amazon;
create table emp2(id int, name varchar(100), city varchar(100));
insert into emp2 values (1, 'abhilash1', 'india'), (2, 'abhilash2', 'indoa'), (3, 'sravani', 'lodon');
select * from emp2;
select concat ('abhi', ' ', 'sree') as fullname ;   
select concat (name, 'place is', city) as details from emp2;
select (concat_ws(' ', 'abhi', 'reddy', 'rudrapu')) as names; 
select concat_ws(',', 'name', city) as details from emp2;
select upper ('Hello') as capital;
select lower ('hELLO') as lower;
select name, upper(name) as capital, city, lower(city) as small from emp2;
select length('Hello') as length;
select char_length('Hello') as char_length;
select id, length(name) as namelength, char_length(name) as namecharlength from emp2;
select substring('abhilash', 2,4);
select name, substring(name, 2,5) as substrr from emp2;
select reverse('abhilash') as rev;
select id, name , reverse(name) as revname from emp2;
select replace ('abhialsh reddy', 'abhilash reddy', 'A')  as replaced_string;
select id , name, replace(name, 'abhilash1', 'I') as replaced_string from emp2;
select 'abhialsh, reddy' like  '%abhilash reddy' as abc;
select * from emp2 where city like '%on';